" use "source pwd/_vimrc" on local file to sync everywhere

syntax on
set autoread
set nocp
set bs=indent,eol,start  " Set backspace
" not allow auto-indent when paste
set paste

filetype plugin on

set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1

" Tag search and generated(F3)
set tags=./tags;/,$HOME/vimtags
"map<F3> :w !ctags -R<CR>
map<F3> :w !ctags *<CR>

" Indent and tab
filetype indent on
set autoindent
set si " smart indent
"set ci
set tabstop=4
set shiftwidth=4  "auto-indent amount when using cindent
set softtabstop=4
set guifont=Menlo:h17

" Search 
set hlsearch
set incsearch
set ignorecase

color desert " Theme
set nu "turn on line number
set ruler " Always show current positions along the bottom
set cursorline
